# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs: 
  steps:
    checkout
    run: cd ../docker_psql/ && docker-compuse up -d
    run: cd api/ && docker-compuse up -d
