# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs: 
  steps:
    checkout
    run: curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
    run: chmod +x ~/docker-compose
    run: sudo mv ~/docker-compose /usr/local/bin/docker-compose
    run: docker-compose up -d ./api/docker-compose.yml
    run: docker-compose up -d ./docker_psql/docker-compose.yml
