# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs: 
  steps:
    checkout
    run: docker-compose up -d ./api/docker-compose.yml
    run: docker-compose up -d ./docker_psql/docker-compose.yml
